name: 'build-test'
on: # rebuild any PRs and main branch changes
    pull_request:
    push:
        branches:
            - test

jobs:
    build: # make sure build/ci work properly
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: |
                yarn
                yarn ci
    test: # make sure the action works on a clean machine without building
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - uses: ./
              with:
                token: ${{ secrets.USER_TOKEN }}
                readme: './README.md'
            - name: Check Status
              run: |
                if [[ "$(git status --porcelain)" != ""]]; then
                git config user.name github-actions[bot]
                git config user.email 41898282+github-actions[bot]@users.noreply.github.com
                git add .
                git commit -m "Update README.md"
                git push
                fi